[2025-03-05T13:34:02.014+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T13:34:02.050+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_categories_dag.crawl_categories scheduled__2025-03-04T00:00:00+00:00 [queued]>
[2025-03-05T13:34:02.075+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_categories_dag.crawl_categories scheduled__2025-03-04T00:00:00+00:00 [queued]>
[2025-03-05T13:34:02.078+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-05T13:34:02.125+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): crawl_categories> on 2025-03-04 00:00:00+00:00
[2025-03-05T13:34:02.147+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=298) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T13:34:02.150+0000] {standard_task_runner.py:72} INFO - Started process 305 to run task
[2025-03-05T13:34:02.147+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'crawl_categories_dag', 'crawl_categories', 'scheduled__2025-03-04T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/crawl_categories_dag.py', '--cfg-path', '/tmp/tmp3j0bbv8h']
[2025-03-05T13:34:02.151+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask crawl_categories
[2025-03-05T13:34:02.188+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-05T13:34:02.270+0000] {task_command.py:467} INFO - Running <TaskInstance: crawl_categories_dag.crawl_categories scheduled__2025-03-04T00:00:00+00:00 [running]> on host 0dad6d57031a
[2025-03-05T13:34:02.276+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-05T13:34:02.486+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawl_categories_dag' AIRFLOW_CTX_TASK_ID='crawl_categories' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-04T00:00:00+00:00'
[2025-03-05T13:34:02.488+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-05T13:34:03.192+0000] {logging_mixin.py:190} INFO - Đã lưu 26 category_id vào file: /opt/***/dags/categories/categories_id.csv
[2025-03-05T13:34:03.194+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-05T13:34:03.209+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-05T13:34:03.210+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=crawl_categories_dag, task_id=crawl_categories, run_id=scheduled__2025-03-04T00:00:00+00:00, execution_date=20250304T000000, start_date=20250305T133402, end_date=20250305T133403
[2025-03-05T13:34:03.315+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T13:34:03.348+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T13:34:03.352+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
